export const SET_ROLE_SESSION = "SET_ROLE_SESSION";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_NAME_RE = "SET_USER_NAME_RE";
export const SET_USER_IMG_RE = "SET_USER_IMG_RE";
export const SET_USER_BOX_ADD = "SET_USER_BOX_ADD";
export const SET_USER_BOX_LOAD = "SET_USER_BOX_LOAD";
export const SET_USER_BOX_NAME_RE = "SET_USER_BOX_NAME_RE";

export const SET_TAB_ADD = "SET_TAB_ADD";

export const SET_TAB_ACTIVE = "SET_TAB_ACTIVE";
export const SET_TAB_GET = "SET_TAB_GET";
export const SET_TAB_UPDATE = "SET_TAB_UPDATE";
export const SET_TAB_DELETE = "SET_TAB_DELETE";
export const SET_TAB_DATE = "SET_TAB_DATE";
export const SET_TAB_VALUE = "SET_TAB_VALUE";
export const SET_TAB_DAILY = "SET_TAB_DAILY";

export const SET_TAB_ADD_VALUE = "SET_TAB_ADD_VALUE";
export const SET_TAB_ADD_DATE = "SET_TAB_ADD_DATE";
export const SET_TAB_ADD_PARAM = "SET_TAB_ADD_PARAM";

export const CREATE_BOX_ADD = "CREATE_BOX_ADD";
export const CREATE_BOX_UPDATE = "CREATE_BOX_UPDATE";
export const CREATE_BOX_UPDATE_TYPE = "CREATE_BOX_UPDATE_TYPE";
export const CREATE_BOX_ADD_PLANTS = "CREATE_BOX_ADD_PLANTS";
export const CREATE_BOX_UPDATE_PLANTS = "CREATE_BOX_UPDATE_PLANTS";

export const SET_LADDER_COMP = "SET_LADDER_COMP";
export const SET_LADDER_BOXACTIVE = "SET_LADDER_BOXACTIVE";

export const SET_LADDER_TOP = "SET_LADDER_TOP";
export const SET_LADDER_USER = "SET_LADDER_USER";

export const SET_COMMENT_BOX = "SET_COMMENT_BOX";

export const SET_FETCH_COMM = "SET_FETCH_COMM";

export const SET_DEVICE_ADMINPANEL_DEFAULT = "SET_DEVICE_ADMINPANEL_DEFAULT";
export const SET_DEVICE_ADMINPANEL_HISTORY = "SET_DEVICE_ADMINPANEL_HISTORY";
export const SET_DEVICE_ADMINPANEL = "SET_DEVICE_ADMINPANEL";
export const SET_CURENT_PHOTO_ADMINPANEL = "SET_CURENT_PHOTO_ADMINPANEL";
export const SET_RATING_PHOTO_ADMINPANEL = "SET_RATING_PHOTO_ADMINPANEL";
export const SET_ADMIN_PANEL_WIDTH = "SET_ADMIN_PANEL_WIDTH";

export const SET_CHAT_DATA = "SET_CHAT_DATA";
